CREATE TABLE IF NOT EXISTS posts (
  post_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  author_id INT NOT NULL REFERENCES users(user_id),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);